from huddle_chat.models import PlaybookDefinition, PlaybookStep

PLAYBOOKS: dict[str, PlaybookDefinition] = {
    "code-task": PlaybookDefinition(
        name="code-task",
        summary="Investigate a coding issue with AI, review proposed action, and capture memory.",
        steps=[
            PlaybookStep(
                id="help-ai",
                title="Review AI command patterns",
                kind="read_only",
                command_template="/help ai",
                requires_input=False,
                placeholders=[],
                expected_result="AI command usage and examples shown.",
            ),
            PlaybookStep(
                id="ai-act",
                title="Ask AI to propose coding actions",
                kind="mutating",
                command_template="/ai --act investigate failing tests in this repo",
                requires_input=False,
                placeholders=[],
                expected_result="AI request persisted; potential pending actions created.",
            ),
            PlaybookStep(
                id="list-actions",
                title="List pending actions",
                kind="read_only",
                command_template="/actions",
                requires_input=False,
                placeholders=[],
                expected_result="Pending action IDs and summaries shown.",
            ),
            PlaybookStep(
                id="inspect-action",
                title="Inspect an action",
                kind="read_only",
                command_template="/action <action-id>",
                requires_input=True,
                placeholders=["<action-id>"],
                expected_result="Action details shown for decision.",
            ),
            PlaybookStep(
                id="capture-memory",
                title="Draft memory from latest AI response",
                kind="mutating",
                command_template="/memory add",
                requires_input=False,
                placeholders=[],
                expected_result="Draft created with confirmation prompt.",
            ),
            PlaybookStep(
                id="confirm-memory",
                title="Confirm draft memory",
                kind="mutating",
                command_template="/memory confirm",
                requires_input=False,
                placeholders=[],
                expected_result="Memory entry saved.",
            ),
        ],
    ),
    "research-task": PlaybookDefinition(
        name="research-task",
        summary="Gather an answer with scoped memory and publish summary from ai-dm.",
        steps=[
            PlaybookStep(
                id="private-ai",
                title="Run private AI query",
                kind="mutating",
                command_template="/ai --private --memory-scope repo,team summarize recent deployment risks",
                requires_input=False,
                placeholders=[],
                expected_result="Response saved in #ai-dm.",
            ),
            PlaybookStep(
                id="join-ai-dm",
                title="Switch to ai-dm room",
                kind="mutating",
                command_template="/join ai-dm",
                requires_input=False,
                placeholders=[],
                expected_result="Local AI-DM room opened.",
            ),
            PlaybookStep(
                id="share-summary",
                title="Share selected messages",
                kind="mutating",
                command_template="/share <target-room> <id|start-end>",
                requires_input=True,
                placeholders=["<target-room>", "<id|start-end>"],
                expected_result="Selected local messages copied into shared room.",
            ),
        ],
    ),
    "safe-tool-run": PlaybookDefinition(
        name="safe-tool-run",
        summary="Review and decide an action safely using explainers.",
        steps=[
            PlaybookStep(
                id="list-actions",
                title="List pending actions",
                kind="read_only",
                command_template="/actions",
                requires_input=False,
                placeholders=[],
                expected_result="Pending actions displayed.",
            ),
            PlaybookStep(
                id="explain-action",
                title="Explain an action risk",
                kind="read_only",
                command_template="/explain action <action-id>",
                requires_input=True,
                placeholders=["<action-id>"],
                expected_result="Concise risk summary and next command shown.",
            ),
            PlaybookStep(
                id="decide-action",
                title="Approve or deny action",
                kind="approval",
                command_template="/approve <action-id>  (or /deny <action-id>)",
                requires_input=True,
                placeholders=["<action-id>"],
                expected_result="Decision persisted and execution begins if approved.",
            ),
        ],
    ),
    "memory-capture": PlaybookDefinition(
        name="memory-capture",
        summary="Capture reusable memory from the latest AI response.",
        steps=[
            PlaybookStep(
                id="draft-memory",
                title="Create memory draft",
                kind="mutating",
                command_template="/memory add",
                requires_input=False,
                placeholders=[],
                expected_result="Draft generated from last AI response.",
            ),
            PlaybookStep(
                id="review-draft",
                title="Review draft",
                kind="read_only",
                command_template="/memory show-draft",
                requires_input=False,
                placeholders=[],
                expected_result="Draft preview displayed.",
            ),
            PlaybookStep(
                id="confirm-draft",
                title="Confirm and save draft",
                kind="mutating",
                command_template="/memory confirm",
                requires_input=False,
                placeholders=[],
                expected_result="Memory entry saved to selected scope.",
            ),
        ],
    ),
}
