from __future__ import annotations

# flake8: noqa: E704

from pathlib import Path
from typing import Any, Protocol


class MessageRepositoryProtocol(Protocol):
    def get_room_dir(self, room: str | None = None) -> Path: ...

    def get_message_file(self, room: str | None = None) -> Path: ...

    def ensure_paths(self) -> None: ...

    def list_rooms(self) -> list[str]: ...


class PresenceRepositoryProtocol(Protocol):
    def get_presence_dir(self, room: str | None = None) -> Path: ...

    def get_presence_path(self, room: str | None = None) -> Path: ...

    def load_presence_entry(
        self, path: Path, fallback_room: str | None, st_mtime: float
    ) -> dict[str, Any] | None: ...

    def get_online_users(
        self, room: str | None = None
    ) -> dict[str, dict[str, Any]]: ...

    def get_online_users_all_rooms(self) -> dict[str, dict[str, Any]]: ...

    def write_presence_atomic(
        self, presence_path: Path, data: dict[str, Any]
    ) -> bool: ...


class MemoryRepositoryProtocol(Protocol):
    def get_memory_dir(self) -> Path: ...

    def get_memory_file(self) -> Path: ...

    def get_private_memory_file(self) -> Path: ...

    def get_repo_memory_file(self) -> Path: ...

    def ensure_memory_paths(self) -> None: ...


class AgentRepositoryProtocol(Protocol):
    def get_agents_dir(self) -> Path: ...

    def get_agent_profiles_dir(self) -> Path: ...

    def get_agent_profile_path(self, profile_id: str) -> Path: ...

    def get_agent_audit_file(self) -> Path: ...

    def ensure_agent_paths(self) -> None: ...

    def append_agent_audit_row(self, row: dict[str, Any]) -> bool: ...


class ActionRepositoryProtocol(Protocol):
    def get_actions_audit_file(self) -> Path: ...

    def append_action_audit_row(self, row: dict[str, Any]) -> bool: ...


class ConfigRepositoryProtocol(Protocol):
    def load_config(self) -> dict[str, Any]: ...

    def save_config(self, payload: dict[str, Any]) -> None: ...

    def load_ai_config(self, default: dict[str, Any]) -> dict[str, Any]: ...

    def save_ai_config(self, payload: dict[str, Any]) -> None: ...

    def get_onboarding_state_path(self) -> Path: ...
